// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppOglas.Models;

namespace WebAppOglas.Migrations
{
    [DbContext(typeof(MvcOglasContext))]
    [Migration("20221204174111_AutoOglas")]
    partial class AutoOglas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppOglas.Models.Automobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnName("cena")
                        .HasColumnType("int");

                    b.Property<string>("Fotografija")
                        .HasColumnName("fotografija")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Godiste")
                        .IsRequired()
                        .HasColumnName("godiste")
                        .HasColumnType("int");

                    b.Property<string>("Gorivo")
                        .IsRequired()
                        .HasColumnName("gorivo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Karoserija")
                        .IsRequired()
                        .HasColumnName("karoserija")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Kontakt")
                        .HasColumnName("kontakt")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnName("marka")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnName("opis")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Snaga")
                        .HasColumnName("snaga")
                        .HasColumnType("int");

                    b.Property<int>("ZapreminaMotora")
                        .HasColumnName("zapremina_motora")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Automobil");
                });
#pragma warning restore 612, 618
        }
    }
}
